# Generated by Django 3.2.18 on 2023-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20230324_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
