# Generated by Django 3.2.18 on 2023-03-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='video_id',
        ),
    ]
